<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_India</name>
   <tag></tag>
   <elementGuidId>0accb15f-566b-4a13-9c00-b0bb09be07d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#address-ui-widgets-countryCode-dropdown-nativeId_102</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='address-ui-widgets-countryCode-dropdown-nativeId_102']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ead353c0-46aa-43b3-91f4-ada3c8761a0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>4671ecdb-17b5-46c5-b7b3-1e5dfeb258ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>4f965331-da42-4017-ad1d-c05c5ca540ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>75bcdcf8-5f68-4f98-8a69-59766a08ef0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>{&quot;stringVal&quot;:&quot;IN&quot;}</value>
      <webElementGuid>b093c988-2e4b-4992-9e7f-81615f562caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address-ui-widgets-countryCode-dropdown-nativeId_102</value>
      <webElementGuid>8e9e7de7-14cf-4845-b947-fe578113ae14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-dropdown-link a-active</value>
      <webElementGuid>c9ece1ca-d8f5-4f75-a711-1671da49849c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>India</value>
      <webElementGuid>37ec2036-a58f-47a7-8d44-f60c78f66a7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address-ui-widgets-countryCode-dropdown-nativeId_102&quot;)</value>
      <webElementGuid>74a71e01-b187-4c44-b10a-896efcd0112f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='address-ui-widgets-countryCode-dropdown-nativeId_102']</value>
      <webElementGuid>764b1c34-180d-4379-9fb1-c218188977ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a-popover-1']/div/div/ul/li[103]/a</value>
      <webElementGuid>da99e25e-c48c-4b39-beeb-0cbdc4bea8df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'India')])[2]</value>
      <webElementGuid>0907be10-0536-4dc9-b3b3-67efcc7ae8c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'address-ui-widgets-countryCode-dropdown-nativeId_102', '&quot;', ')')])[1]/following::a[103]</value>
      <webElementGuid>7e29cf17-a96e-4e2c-a0a9-10bb1200f7c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How are delivery costs calculated?'])[1]/following::a[103]</value>
      <webElementGuid>dea5ff74-0a8a-44f5-aa26-11b6a1afc738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[104]</value>
      <webElementGuid>e29cc58a-bd9e-4953-9f34-d310b72f71b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[103]/a</value>
      <webElementGuid>7927359f-e9de-43cb-958e-d4d14f094c80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and @id = 'address-ui-widgets-countryCode-dropdown-nativeId_102' and (text() = 'India' or . = 'India')]</value>
      <webElementGuid>d877165e-a105-4d77-b413-8ba1ba1962c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
