<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_TELANGANA</name>
   <tag></tag>
   <elementGuidId>a1d4a193-74c1-4857-bf1e-30370f68d265</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#address-ui-widgets-enterAddressStateOrRegion-dropdown-nativeId_31</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='address-ui-widgets-enterAddressStateOrRegion-dropdown-nativeId_31']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fa670cb6-f8e9-4ee3-9e4f-746256024c92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>a4d2d1ba-f318-49ab-9b20-1369061b146b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>39ebe785-9fd6-4d9a-9d1e-c83a3657d896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>99fc49eb-ad0e-43cc-85fc-83455669ffa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>{&quot;stringVal&quot;:&quot;TELANGANA&quot;}</value>
      <webElementGuid>0d25563f-2143-47a5-b2be-eadcfef4be1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address-ui-widgets-enterAddressStateOrRegion-dropdown-nativeId_31</value>
      <webElementGuid>28d89e60-71a9-4858-95fa-317f8979404b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-dropdown-link a-active</value>
      <webElementGuid>a460b878-9719-4934-812e-3a0633acf131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TELANGANA</value>
      <webElementGuid>f317f796-5db0-4d6b-a748-d76201a888bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address-ui-widgets-enterAddressStateOrRegion-dropdown-nativeId_31&quot;)</value>
      <webElementGuid>783ea5e7-9456-40a1-a006-876c2d26644c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='address-ui-widgets-enterAddressStateOrRegion-dropdown-nativeId_31']</value>
      <webElementGuid>388c2480-4588-4072-a376-a5b2eb0f9eda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a-popover-2']/div/div/ul/li[32]/a</value>
      <webElementGuid>33be1b80-428b-44e8-9d87-969510a00998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'TELANGANA')]</value>
      <webElementGuid>a77c8965-138e-4188-9daf-5aafabce8d35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'address-ui-widgets-enterAddressStateOrRegion-dropdown-nativeId_31', '&quot;', ')')])[1]/following::a[278]</value>
      <webElementGuid>6f81c8e3-08dc-4cfe-9ec6-b72b77e3d7d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How are delivery costs calculated?'])[1]/following::a[278]</value>
      <webElementGuid>91631130-9a27-4e5d-97f2-2ad1cf39209a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[279]</value>
      <webElementGuid>041137f4-5b69-49d8-b8d7-12cf8e27ba46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/ul/li[32]/a</value>
      <webElementGuid>33cc3870-05a6-42bd-9cdf-038119b92bd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and @id = 'address-ui-widgets-enterAddressStateOrRegion-dropdown-nativeId_31' and (text() = 'TELANGANA' or . = 'TELANGANA')]</value>
      <webElementGuid>aba8294a-a85f-49e1-bc43-76bdd31eab70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
