<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Delivery instructions (optional)_a-icon a_cc7932</name>
   <tag></tag>
   <elementGuidId>40afa529-41ec-4872-a81f-a52a58f81873</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.a-icon.a-icon-expand</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='address-ui-widgets-enterAddressFormContainer']/div[10]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>445ab0d8-b4a1-4852-8610-127b7cb13bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-icon a-icon-expand</value>
      <webElementGuid>b35497d2-0ff5-4475-8a31-78117e988582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address-ui-widgets-enterAddressFormContainer&quot;)/div[@class=&quot;a-row a-expander-container a-expander-inline-container address-ui-widgets-desktop-delivery-instructions-expander&quot;]/a[@class=&quot;a-expander-header a-declarative a-expander-inline-header a-link-expander&quot;]/i[@class=&quot;a-icon a-icon-expand&quot;]</value>
      <webElementGuid>f98675ef-1382-4651-a2af-628b8f8856ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='address-ui-widgets-enterAddressFormContainer']/div[10]/a/i</value>
      <webElementGuid>99147137-95bc-4b56-ae45-e9613ba1cd04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/i</value>
      <webElementGuid>8493b69b-db82-44eb-971b-c83eeb1965fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
