<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Flat, House no., Building, Company, A_6a51d1</name>
   <tag></tag>
   <elementGuidId>fe432392-8c5f-4fd9-9f62-62d94a750319</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#address-ui-widgets-enterAddressLine1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address-ui-widgets-enterAddressLine1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d1eb8c96-711b-454c-8d45-ac6f0c32c612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>416edaf0-bac5-40a8-a12a-9213aac9fe31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>8221f9cb-a226-4598-9f4b-fd9aa955628c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address-ui-widgets-enterAddressLine1</value>
      <webElementGuid>0483e40b-0324-4da7-8c00-89510184bfda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address-ui-widgets-enterAddressLine1</value>
      <webElementGuid>ade41124-6d09-4340-882f-9b1164e772aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ed583e3c-7d4c-4a8b-866a-c77ab06d791a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-input-text address-ui-widgets-desktop-form-field-full-width addrui-form-text-input</value>
      <webElementGuid>ccbe3a50-6e2d-4c2d-a3f6-ebbcbe6e08cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>address-ui-widgets-enterAddressLine1</value>
      <webElementGuid>d04ee6ed-9a10-4139-be2c-c82a3a99ab00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address-ui-widgets-enterAddressLine1&quot;)</value>
      <webElementGuid>344e0504-00b9-4490-9463-c66ca3547918</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='address-ui-widgets-enterAddressLine1']</value>
      <webElementGuid>6ef93c69-3017-427a-9212-70b3cab012b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='address-ui-widgets-enterAddressFormContainer']/div[7]/div/div[10]/input</value>
      <webElementGuid>acf2ed01-bcdf-46e2-a767-f4ab250c8030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/input</value>
      <webElementGuid>4010b345-8af3-455e-9192-e3bcd40823e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'address-ui-widgets-enterAddressLine1' and @name = 'address-ui-widgets-enterAddressLine1']</value>
      <webElementGuid>8c3b2978-f747-4912-8805-2fa186e02e70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
