<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Your addresses_submissionURL</name>
   <tag></tag>
   <elementGuidId>39c786c5-9f5b-401a-8f70-e768b3f8ed54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;submissionURL&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='submissionURL']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4dff7a3e-69b2-4561-8c52-16de0cbf4371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>17c9bc7f-551b-4a65-bcbb-4a46863088e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submissionURL</value>
      <webElementGuid>c0d1ee1a-0c36-4fbe-b4f4-5876f24025e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>/checkout/p/p-404-0490870-4795569/address/shiptodestination/ref=chk_addr_select_1_customer?_encoding=UTF8&amp;abBusinessGroupId=&amp;action=select-shipping&amp;addressID=IOYU37JE53XFYXD4DYPEG125G9DW85LLIA27ILL58WD9G5HPXTQ2EIA2OXF73QE2&amp;enableDeliveryPreferences=1&amp;fromAnywhere=0&amp;numberOfDistinctItems=1&amp;purchaseId=404-0490870-4795569&amp;requestToken=</value>
      <webElementGuid>f9618e08-d7bf-485e-8709-1d5aab476209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address-list&quot;)/div[@class=&quot;a-box-group a-spacing-small&quot;]/div[@class=&quot;a-box&quot;]/div[@class=&quot;a-box-inner&quot;]/fieldset[1]/div[@class=&quot;a-row address-row list-address-selected&quot;]/span[@class=&quot;a-declarative&quot;]/div[@class=&quot;a-radio&quot;]/label[1]/input[1]</value>
      <webElementGuid>ed65eaca-f496-4374-900c-962676eda22b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='submissionURL']</value>
      <webElementGuid>4be72bdc-b257-4d4d-a1f9-5f3b44f1baf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='address-list']/div/div/div/fieldset/div/span/div/label/input</value>
      <webElementGuid>5878d12b-f2d5-4bab-83d1-098ba6c20490</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>e635bac6-ec16-4e68-9636-8c23be18377f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'submissionURL']</value>
      <webElementGuid>d43a61cd-79a7-4e4d-ac7a-ecf69b3b0b2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
