<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Area, Street, Sector, Village_address_fb368b</name>
   <tag></tag>
   <elementGuidId>19ebf9a5-b3d3-4441-afde-7be13f9b5fcf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#address-ui-widgets-enterAddressLine2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address-ui-widgets-enterAddressLine2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff5fca96-974d-4f40-ac56-3be54d04d890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c4bdb123-29a5-4977-9c64-6eed2f28fe05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>23a96807-6a68-4559-8f81-0b82a502d639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address-ui-widgets-enterAddressLine2</value>
      <webElementGuid>59c34229-87be-44da-b42e-d401faae8330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address-ui-widgets-enterAddressLine2</value>
      <webElementGuid>507c8de7-7847-457b-8f3e-b99f3c9b387e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c965cd76-e750-4974-9879-0de2d353d533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-input-text address-ui-widgets-desktop-form-field-full-width addrui-form-text-input</value>
      <webElementGuid>57a04424-d5a8-41e8-88b4-d6c6c3fb39f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>address-ui-widgets-enterAddressLine2</value>
      <webElementGuid>0b9a00ec-a91a-4578-bb92-12bfa1bde2bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address-ui-widgets-enterAddressLine2&quot;)</value>
      <webElementGuid>d0002725-8005-487a-a7ea-0008ff770295</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='address-ui-widgets-enterAddressLine2']</value>
      <webElementGuid>b89be9e0-6820-46c0-833b-14d82fa86fb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='address-ui-widgets-enterAddressFormContainer']/div[7]/div/div[12]/input</value>
      <webElementGuid>9a5777b7-510f-47b2-96b2-4c07b4335254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/input</value>
      <webElementGuid>ce29fa99-e12b-4468-be05-03bcca5d7f6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'address-ui-widgets-enterAddressLine2' and @name = 'address-ui-widgets-enterAddressLine2']</value>
      <webElementGuid>18427900-e0fb-4d2f-b5cc-aca67a5684db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
