<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_India_1</name>
   <tag></tag>
   <elementGuidId>ea72bea6-0305-44b8-8e2c-cf44b23fd691</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#address-ui-widgets-countryCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='address-ui-widgets-countryCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>853c1bcd-2c9f-45fc-bf09-999ead99d401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>15565d18-151d-4184-a282-0f0c4df1c4dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address-ui-widgets-countryCode</value>
      <webElementGuid>53df5cee-be5d-44ea-8fdd-6f1523bccc03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-a-class</name>
      <type>Main</type>
      <value>address-ui-widgets-desktop-form-field-full-width</value>
      <webElementGuid>628e925a-ccc4-47e2-ad0c-8da816844611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button a-button-dropdown a-spacing-none  address-ui-widgets-desktop-form-field-full-width</value>
      <webElementGuid>4bb86617-3eed-4369-a1c2-b3893f279069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0b9f49c4-35ba-4572-af66-38c06d48430f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>India</value>
      <webElementGuid>8ba87cda-8a94-4bea-a81f-7fa81628f92c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address-ui-widgets-countryCode&quot;)</value>
      <webElementGuid>2946d192-12cd-4397-8e49-f9f420584eb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='address-ui-widgets-countryCode']</value>
      <webElementGuid>3a67dc0e-7cfc-4f81-bcd4-ac6e2e05636b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='address-ui-widgets-enterAddressFormContainer']/div[7]/div/div[2]/span/span</value>
      <webElementGuid>c80d55ea-a7de-4be3-b3ef-854a6a143778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country/Region'])[1]/following::span[2]</value>
      <webElementGuid>c7aba495-b872-43a5-9954-e1465d78331e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hmm. We could not find your device’s location. Please enter the address manually.'])[1]/following::span[16]</value>
      <webElementGuid>01a263e5-1441-4114-9f9a-a141c4ea63e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unable to change country, please try again'])[1]/preceding::span[4]</value>
      <webElementGuid>bb91afb0-1264-4138-b081-1126eacddf5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[2]/span/span</value>
      <webElementGuid>e5dd53bd-0cbe-4f50-9821-ecc7422a094f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'address-ui-widgets-countryCode' and (text() = 'India' or . = 'India')]</value>
      <webElementGuid>a312ff7f-a7ec-4a40-a83b-51c7ed759034</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
