<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Shipping cost, delivery date and orde_a6d45b</name>
   <tag></tag>
   <elementGuidId>4e436795-e507-4a84-8840-f33967ef7c45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#buy-now-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='buy-now-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>57d80094-bb34-4cdc-8fd7-0ec5deab97fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buy-now-button</value>
      <webElementGuid>c9ff54d6-fac3-44bb-9435-72b35f7d88ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submit.buy-now</value>
      <webElementGuid>30255a58-a764-4238-b283-3408d6667aa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Buy Now</value>
      <webElementGuid>b5d853d9-cd70-4bf8-a600-88e72c78ee3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hover</name>
      <type>Main</type>
      <value>Select &lt;b>__dims__&lt;/b> from the left&lt;br> to Buy</value>
      <webElementGuid>e21c4656-f49b-4707-b28e-6d390e99c0bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>380a9842-2f98-4b70-b825-d8cecd6ee4f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>20c8386c-4354-49bd-a34b-ac254f65c3ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>submit.buy-now-announce</value>
      <webElementGuid>8de4604d-9ab5-4135-be79-d3a60dc66021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buy-now-button&quot;)</value>
      <webElementGuid>b7c5f798-5ef9-46f8-97f8-526f24ea901c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='buy-now-button']</value>
      <webElementGuid>854865e2-5f30-4ff1-a3cf-4fad9c89b6dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='submit.buy-now']/span/input</value>
      <webElementGuid>9e095be8-441e-43ec-b323-010f54464834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/span/input</value>
      <webElementGuid>ce261191-3fe3-41d8-969b-e3bc188eeb70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'buy-now-button' and @name = 'submit.buy-now' and @title = 'Buy Now' and @type = 'submit']</value>
      <webElementGuid>8567cdba-9702-4c39-a968-d753ee0b2874</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
