<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Featured_a-section octopus-dlp-image-shield</name>
   <tag></tag>
   <elementGuidId>a4fe2366-1c09-4f62-a7be-4f59d3d244c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='octopus-dlp-asin-stream']/ul/li/span/div/div/a/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.a-section.octopus-dlp-image-shield</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0ec8edeb-e572-4e82-af15-0420e04edc26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-section octopus-dlp-image-shield</value>
      <webElementGuid>01fece73-ca2d-479d-b383-52fbb1880b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;octopus-dlp-asin-stream&quot;)/ul[@class=&quot;a-unordered-list a-nostyle a-horizontal a-spacing-none&quot;]/li[@class=&quot;a-list-normal a-spacing-none no-margin-right overflow-hidden octopus-response-li-width&quot;]/span[@class=&quot;a-list-item&quot;]/div[@class=&quot;a-section octopus-dlp-asin-section&quot;]/div[@class=&quot;a-section a-spacing-base a-text-center octopus-dlp-image-section&quot;]/a[@class=&quot;a-link-normal&quot;]/div[@class=&quot;a-section octopus-dlp-image-shield&quot;]</value>
      <webElementGuid>75eb6f70-8ffb-43a2-acf7-9a625d736c1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='octopus-dlp-asin-stream']/ul/li/span/div/div/a/div</value>
      <webElementGuid>b1e2e105-2b0f-464e-9900-215b0768b3f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div/a/div</value>
      <webElementGuid>156821a4-0ae7-4d90-a3a9-9a64c6099787</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
