<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_All</name>
   <tag></tag>
   <elementGuidId>fb8435c0-1c0e-49b7-bc51-220c541721ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav-hamburger-menu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nav-hamburger-menu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c2aca78d-e9f7-49ca-9f9c-65e4c539c2bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript: void(0)</value>
      <webElementGuid>b955b8f7-e3f7-47d9-a40b-528dbf5db425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-hamburger-menu</value>
      <webElementGuid>f0ec654d-2a8b-4a47-a216-8b2976aa8070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0d254a42-ca07-4022-9c39-eeed891eea17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Open Menu</value>
      <webElementGuid>6a5a1695-0e22-4a14-afca-e8dd5fa899de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-type</name>
      <type>Main</type>
      <value>widget</value>
      <webElementGuid>85783a65-5cb1-4ef4-bc51-604b7a8d8c78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-slot-id</name>
      <type>Main</type>
      <value>HamburgerMenuDesktop</value>
      <webElementGuid>6645effe-9520-4165-9afb-d15191d3c109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-interaction-events</name>
      <type>Main</type>
      <value>click</value>
      <webElementGuid>76d13b7f-6abd-4d64-b8fc-38aba07f89b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>klfgvr-qcziyz-soa4uy-enwyl4</value>
      <webElementGuid>62b3753f-e051-4e22-8424-096baff9111d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    
    All
  </value>
      <webElementGuid>3f00cfa3-1bec-4059-a1cd-6cd87e384b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-hamburger-menu&quot;)</value>
      <webElementGuid>b395f7dc-642e-44c0-bd22-cac9e832e9dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='nav-hamburger-menu']</value>
      <webElementGuid>e2bb4764-556a-4e79-8c42-55411fb3a0bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-main']/div/a</value>
      <webElementGuid>0e42cbf6-4c97-4437-a817-41ea8a9b0e5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&amp; Orders'])[1]/following::a[2]</value>
      <webElementGuid>65f20297-7f40-4682-8d90-ddda587b265f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Returns'])[1]/following::a[2]</value>
      <webElementGuid>0f60df9f-7c25-4687-a9e8-38a1f532d573</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fresh'])[1]/preceding::a[1]</value>
      <webElementGuid>e8777778-86dd-4710-af7f-f073abfa395c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript: void(0)')]</value>
      <webElementGuid>240c354c-c1e6-4b4c-85d6-2789b555d5f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>09a8f658-b96e-489b-83d0-69da15a8b0c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript: void(0)' and @id = 'nav-hamburger-menu' and (text() = '
    
    All
  ' or . = '
    
    All
  ')]</value>
      <webElementGuid>add6d109-ce6c-4bab-a8b4-79edcbe8681e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
