<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Cart</name>
   <tag></tag>
   <elementGuidId>e27ad6a1-f026-4df6-b76e-8039e2d6e363</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='attach-sidesheet-view-cart-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#attach-sidesheet-view-cart-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a9e9953f-67fd-41ef-8b6c-7b302e371e45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>attach-sidesheet-view-cart-button</value>
      <webElementGuid>ec4ba2a5-bfbe-4e6c-8722-5d9826e5e44b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button a-button-base attach-button-large attach-cart-button</value>
      <webElementGuid>c80fd935-947f-49e4-be19-1997c4d8a4da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>    Cart   </value>
      <webElementGuid>38db23c3-0ce5-4011-976f-6d86015801f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attach-sidesheet-view-cart-button&quot;)</value>
      <webElementGuid>ecb6ff65-6b93-4290-bc96-9e6cc764940d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='attach-sidesheet-view-cart-button']</value>
      <webElementGuid>3a14576b-00fc-4f99-b68c-abcfe7cac410</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='attach-view-cart-button-form']/span</value>
      <webElementGuid>3eda51af-a183-4d1c-8222-7d39ff838502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='There was a problem retrieving the contents of your cart.'])[1]/following::span[1]</value>
      <webElementGuid>5de767e7-5332-45a1-8e21-a16a77e64770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹1,219.00'])[7]/following::span[2]</value>
      <webElementGuid>9661b832-f858-4670-a820-0615fe594aeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proceed to checkout (1 item)'])[1]/preceding::span[3]</value>
      <webElementGuid>5fa3fdab-06c8-4a71-8fdf-c56481eb4953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='An error occurred when processing your request.'])[1]/preceding::span[8]</value>
      <webElementGuid>2a18257c-a432-4e79-80d4-1fa0ea31add1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/form/span</value>
      <webElementGuid>690132bb-d736-4edb-9831-c0a1b0aa0fca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'attach-sidesheet-view-cart-button' and (text() = '    Cart   ' or . = '    Cart   ')]</value>
      <webElementGuid>d271f394-9212-43d8-b502-0cc7458c1f59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
