<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ICICI Bank</name>
   <tag></tag>
   <elementGuidId>a9e8afa3-33b8-43ef-85c3-6fcb595953e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pp-91CgmX-106_3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='pp-91CgmX-106_3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>be428cec-a9b9-4b95-8cd1-08f5938ee561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>89adb5fa-a534-4129-bb07-aab727527087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>50dbc5f1-b01f-4d5d-a261-39fc864168ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>639c674b-bbd7-429f-b72d-f27e87a8b8dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>{&quot;stringVal&quot;:&quot;ICI DIRECT&quot;}</value>
      <webElementGuid>5978e8f2-c807-419b-b944-eedcca86f526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pp-91CgmX-106_3</value>
      <webElementGuid>412485fe-ff91-4de6-8d11-1b74529e7d13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-dropdown-link</value>
      <webElementGuid>04a1eb10-f90b-4dc4-b6ff-27d47520aed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ICICI Bank</value>
      <webElementGuid>536857dc-5b47-4d44-a34a-7e19efc5c793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pp-91CgmX-106_3&quot;)</value>
      <webElementGuid>b8911a6a-4e50-455e-88fc-187404673ca3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='pp-91CgmX-106_3']</value>
      <webElementGuid>85e753af-e1d5-4de3-b4db-d7bf8585e7c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a-popover-5']/div/div/ul/li[4]/a</value>
      <webElementGuid>46163b14-6696-408e-90aa-7d013bee8117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ICICI Bank')]</value>
      <webElementGuid>09c58816-f90e-4a30-901a-f92520593270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'pp-91CgmX-106_3', '&quot;', ')')])[1]/following::a[286]</value>
      <webElementGuid>0e2be069-6cf8-4b0a-83c2-f43b22483024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How are delivery costs calculated?'])[1]/following::a[286]</value>
      <webElementGuid>d1db5f41-a2a1-4bbe-bf92-e158b88fcb48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[286]</value>
      <webElementGuid>78292f66-d35a-468c-842e-53394abfe943</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/ul/li[4]/a</value>
      <webElementGuid>40bd70b4-8b44-4fa4-82ba-9ceef339b424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and @id = 'pp-91CgmX-106_3' and (text() = 'ICICI Bank' or . = 'ICICI Bank')]</value>
      <webElementGuid>8e1a37ff-a572-4efe-802f-3b751a4691fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
