<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Amazon accepts all major credit   car_451b00</name>
   <tag></tag>
   <elementGuidId>603317f3-80ac-4997-8fb5-f6b2e45ccb79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pp-91CgmX-103</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pp-91CgmX-103']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>86acb19b-ee83-4a18-9b6a-f5fe308b8262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pp-91CgmX-103</value>
      <webElementGuid>068570c0-c4ed-4521-9bdd-d9ad928b810f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>59f9962e-7ddc-44f2-ad23-15abb42f24fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ppw-instrumentRowSelection</value>
      <webElementGuid>dba7a60a-0472-431d-b325-020072549ae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>instrumentId=NetBanking&amp;isExpired=false&amp;paymentMethod=NB&amp;tfxEligible=false</value>
      <webElementGuid>17c00857-0060-4f68-b61d-836348fa7752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pp-91CgmX-103&quot;)</value>
      <webElementGuid>d04488fb-aeb7-4d98-b25b-523077041f6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pp-91CgmX-103']</value>
      <webElementGuid>cb696195-973f-4b81-9890-df45f1ccb55e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pp-91CgmX-102']/div/div/div/div/span/div/label/input</value>
      <webElementGuid>4802e597-0288-4698-9c92-06baf0c1cadf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/span/div/label/input</value>
      <webElementGuid>6af0e3fc-71ae-4d9e-8be8-936612d65145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pp-91CgmX-103' and @type = 'radio' and @name = 'ppw-instrumentRowSelection']</value>
      <webElementGuid>398e95c3-2d14-4b39-941a-ceae7d5eeb37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
