<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please enter your UPI ID_ppw-widgetEv_331406</name>
   <tag></tag>
   <elementGuidId>92bdca8f-8667-428e-b96e-f9950cbe1a35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;ppw-widgetEvent:ValidateUpiIdEvent&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='ppw-widgetEvent:ValidateUpiIdEvent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0813c88f-67a2-47ff-a494-40559bac2583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ppw-widgetEvent:ValidateUpiIdEvent</value>
      <webElementGuid>73c60c48-a703-4d3b-ad67-c1374fc7f948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>8c3f29f8-31af-43b7-bbfa-d2f36e40fa3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>900e3d43-3a78-4e99-8354-4ea70a35fe7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>pp-91CgmX-112-announce</value>
      <webElementGuid>95159e0f-5c99-4b04-ab4d-f9a2c1a3f6af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pp-91CgmX-112&quot;)/span[@class=&quot;a-button-inner&quot;]/input[@class=&quot;a-button-input&quot;]</value>
      <webElementGuid>1bfe7f82-df33-4fef-8024-937d8ee4d1dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='ppw-widgetEvent:ValidateUpiIdEvent']</value>
      <webElementGuid>80160d54-d2fc-4150-b3f0-1b6f4aecfabc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='pp-91CgmX-112']/span/input</value>
      <webElementGuid>25ebc849-f2ac-409a-a97f-a9a4e047c2ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/span/input</value>
      <webElementGuid>8028f7ee-1b8b-4141-82f6-b94efb6090fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ppw-widgetEvent:ValidateUpiIdEvent' and @type = 'submit']</value>
      <webElementGuid>9bd02dfd-b1b6-4b61-90ce-452c2f6aa2b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
