<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Your available balance_ppw-claimCodeA_bab66d</name>
   <tag></tag>
   <elementGuidId>dfd55841-2971-454a-a0d5-d703334ff476</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;ppw-claimCodeApplyPressed&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='ppw-claimCodeApplyPressed']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>be2c5f3d-27c3-4a0f-960f-4ddbade64cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ppw-claimCodeApplyPressed</value>
      <webElementGuid>fc5a58ae-1f51-410c-b835-ccdf2b7a97fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input a-button-text</value>
      <webElementGuid>5e56e68a-338c-41da-a81d-9a8186442b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>6199daa8-784b-40a2-bd3f-7fb8c8bfad8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Apply</value>
      <webElementGuid>51f9a65f-a757-4fb6-bd85-76bb3ff983d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>pp-BRtLRY-95-announce</value>
      <webElementGuid>5ded5705-405d-49b4-859a-b4414eef6c30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pp-BRtLRY-95&quot;)/span[@class=&quot;a-button-inner&quot;]/input[@class=&quot;a-button-input a-button-text&quot;]</value>
      <webElementGuid>440e2086-001a-4a7d-8563-f67eb778203f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='ppw-claimCodeApplyPressed']</value>
      <webElementGuid>90ce4fc9-aaa2-45d5-ba50-0513ff1deab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='pp-BRtLRY-95']/span/input</value>
      <webElementGuid>7d7bf8a9-adde-40b9-87e1-ca9158e6b5ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[4]/span/input</value>
      <webElementGuid>b6ea1c3b-1794-44a8-b245-7104a32c4541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ppw-claimCodeApplyPressed' and @type = 'submit']</value>
      <webElementGuid>77ff16a3-35ba-40e5-94eb-f8cef5d5a95d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
