<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Your available balance_ppw-claimCode</name>
   <tag></tag>
   <elementGuidId>45d2a71a-964c-4f7a-8c57-93ead397500d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pp-BRtLRY-94</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pp-BRtLRY-94']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d1af2c8-6afe-41a6-99db-92491570e9b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4d9148f1-89bc-460d-a2db-4c9a123a973f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>45e04a5e-ef8c-452c-bf12-083de2e10f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pp-BRtLRY-94</value>
      <webElementGuid>78cc5ba1-5113-4996-9bd0-ea1efe0758c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d7a7d27b-f408-4b9b-94ba-ae21679d6888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Code</value>
      <webElementGuid>fc7a18df-17af-4c29-8e7c-53ba4919a8a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ppw-claimCode</value>
      <webElementGuid>49b8ab0a-8e20-4545-a800-9343132dbcb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8d1017eb-7739-4cac-9662-53d4a4e8225d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-input-text a-form-normal a-width-large a-span9 pmts-claim-code</value>
      <webElementGuid>c98dadd8-a62d-4e6e-b302-12b251d720a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pp-BRtLRY-94&quot;)</value>
      <webElementGuid>9f1bb3a3-7b4d-4151-a1aa-04b77ece18be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pp-BRtLRY-94']</value>
      <webElementGuid>2e862813-85c3-4b39-84db-02fb9d5e16ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='pp-BRtLRY-93']/div/div/div/fieldset/div/div[2]/div/input</value>
      <webElementGuid>781a7565-0da6-4b65-940b-138cddbd7b65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>bc71a3c1-a7f5-419d-8c9f-f945b4b75329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'pp-BRtLRY-94' and @placeholder = 'Enter Code' and @name = 'ppw-claimCode']</value>
      <webElementGuid>694a355e-185e-442e-8834-fb3447371d4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
