<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Another payment method_ppw-instrument_d02253</name>
   <tag></tag>
   <elementGuidId>d92b67a0-fe92-422b-9a52-12942f0500bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pp-91CgmX-97</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pp-91CgmX-97']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7a4c7984-1a9c-498c-b6c0-4d12a5b01462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pp-91CgmX-97</value>
      <webElementGuid>624d597b-d2dd-4efe-b51f-55fc10372166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>7d822d43-1bbc-4d77-b4eb-06b894893a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ppw-instrumentRowSelection</value>
      <webElementGuid>fb101b0f-e7a0-4962-a2d2-63d69fbaa2fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>SelectableAddCreditCard</value>
      <webElementGuid>2bd4984c-7ac8-4313-a912-de2c1785521d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pp-91CgmX-97&quot;)</value>
      <webElementGuid>5e7b45dc-1159-4942-a230-347e889dd082</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pp-91CgmX-97']</value>
      <webElementGuid>ce77991d-ca55-4606-91b0-3da5730f91ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pp-91CgmX-96']/div/div/div/div/div/span/div/label/input</value>
      <webElementGuid>b8a9621a-fbdc-4ad4-ac31-2b76c963dde4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>b9db42e1-0d07-4b61-822f-17cd44dafb40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pp-91CgmX-97' and @type = 'radio' and @name = 'ppw-instrumentRowSelection']</value>
      <webElementGuid>48fcbd4f-1bf9-4f4b-90fb-288b428f0698</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
