<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Cash on DeliveryPay on Delivery</name>
   <tag></tag>
   <elementGuidId>44152d59-1c21-4e05-9153-4d4ace4aaf27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pp-91CgmX-140 > div.a-box.pmts-instrument-box > div.a-box-inner.a-padding-small > div.a-fixed-left-grid > div.a-fixed-left-grid-inner > div.a-fixed-left-grid-col.a-col-left > div.a-radio > label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pp-91CgmX-140']/div/div/div/div/div/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>457e717b-7a81-4bb2-978b-070ba8b889e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>pp-91CgmX-141</value>
      <webElementGuid>ec73aaf9-4cdd-43c8-826c-6a31d0d6aebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cash on Delivery/Pay on Delivery</value>
      <webElementGuid>26f4eed2-0523-4b0f-9eca-0e7d32252bbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pp-91CgmX-140&quot;)/div[@class=&quot;a-box pmts-instrument-box&quot;]/div[@class=&quot;a-box-inner a-padding-small&quot;]/div[@class=&quot;a-fixed-left-grid&quot;]/div[@class=&quot;a-fixed-left-grid-inner&quot;]/div[@class=&quot;a-fixed-left-grid-col a-col-left&quot;]/div[@class=&quot;a-radio&quot;]/label[1]</value>
      <webElementGuid>5d68fdea-54ac-4105-ba1f-8b2ba756425e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pp-91CgmX-140']/div/div/div/div/div/div/label</value>
      <webElementGuid>32c15c7c-eb1f-42a2-8eb1-c5afd36556c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Why?'])[2]/following::label[1]</value>
      <webElementGuid>818c9221-e884-4f6a-9ea8-6eef4d163aa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Why?'])[1]/following::label[1]</value>
      <webElementGuid>e9761e88-5074-42ab-b77f-d0f9f8a1ad11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cash on Delivery/Pay on Delivery'])[2]/preceding::label[1]</value>
      <webElementGuid>e3816039-03a0-47f2-a457-a6064ef52253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div/div/label</value>
      <webElementGuid>ba1a331d-34a0-4c67-923e-b0b73883395b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Cash on Delivery/Pay on Delivery' or . = 'Cash on Delivery/Pay on Delivery')]</value>
      <webElementGuid>5674a07e-52c3-464d-989c-16907e916dc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
